name: "🐞 Bug in the App"
description: "Something isn't working in the UI to Skeleton tool."
title: "[Bug] - "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What went wrong?
      description: Describe the problem as clearly as possible.
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open the tool
        2. Click on...
        3. See error
      required: true

  - type: input
    id: version
    attributes:
      label: Tool Version (or link)
      placeholder: "v1.2.3 or https://your-tool-url.com"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: Windows 10 / macOS 14
        - Browser: Chrome 124
        - Node.js: 20.x (if used)
