name: Report a bug
description: Something is not working? Report a bug
title: "[Bug]: "
labels: [":bug: bug", ":eyes: triage"]
body:

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: >-
        Explain where the UI to Skeleton tool does not behave as expected.
        Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: >-
        Tell us exactly how to reproduce the issue.
      placeholder: |-
        1. Go to the tool
        2. Paste this UI code: [...]
        3. Click "Generate"
        4. Observe the issue
    validations:
      required: true

  - type: textarea
    id: ui-code
    attributes:
      label: UI Code (if relevant)
      description: >-
        Paste the exact UI code that triggered the issue, if applicable.
      render: shell

  - type: textarea
    id: skeleton-output
    attributes:
      label: Generated Skeleton (optional)
      description: >-
        If the tool generated incorrect output, paste it here.
      render: shell

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: >-
        Include your browser, OS, and tool version (if applicable).
      placeholder: |-
        Browser: Chrome 124  
        OS: Windows 11  
        Tool version: latest (web)
    validations:
      required: true
