name: Report a bug
description: Something is not working? Report a bug
title: "[Bug]: "
labels: [":bug: bug", ":eyes: triage"]
body:

  - type: textarea
    id: context
    attributes:
      label: Context
      description: >-
        This field is optional. You may provide additional context for the bug
        you want to report, helping us to understand what you are working on and
        what you are trying to achieve. If the context is not relevant, you can
        leave this field empty.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: >-
        Explain where the UI to Skeleton tool does not behave as you would expect it to.
        Be as specific as possible. If you found a workaround or fix, please let us (and others) know.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: >-
        Please create a __.zip file__ with a __minimal reproduction__ or include the exact input/output that reproduces the bug.
      placeholder: |-
        Drag and drop the .zip file with minimal reproduction here or paste UI code/skeleton output.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Provide a detailed list of instructions, guiding us through the steps to recreate the issue.
        Be as specific as possible.
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment & Versions
      description: >-
        Please include relevant version information:
      placeholder: |-
        UI to Skeleton version: ...
        Node.js version (if used): ...
        Browser & version: ...
        Operating system: ...
    validations:
      required: true
