name: "✨ Feature Request"
description: "Suggest an idea to improve the UI to Skeleton tool"
title: "[Feature] - "
labels: [enhancement]
body:
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: What problem does it solve?
      description: Describe the benefit or context of the feature.
    validations:
      required: true

  - type: textarea
    id: proposed-structure
    attributes:
      label: Proposed project structure or output format (optional)
      description: Suggest how the skeleton generation or project structure should change or improve.
    validations:
      required: false

