import type { Metadata } from "next";
import { Plus_Jakarta_Sans, } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Script from "next/script.js"
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${plusJakartaSans.variable} antialiased`}>
      <body
      >
        <Toaster />
        {children}
         <Script
        src="https://analytics-2.zeenku.com/api/script.js"
        data-site-id="7866d17130af"
        defer
        strategy="afterInteractive"
      />
      </body>
    </html>
  );
}
